# Generated by Django 5.0.7 on 2024-08-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("course_name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("joining_date", models.DateField()),
                ("contact_number", models.CharField(max_length=15)),
            ],
        ),
    ]
