# Generated by Django 5.0.7 on 2024-08-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_location",
                    models.CharField(
                        choices=[
                            ("hyderabad", "hyderabad"),
                            ("bangalore", "bangalore"),
                            ("chennai", "chennai"),
                            ("mumbai", "mumbai"),
                            ("kadapa", "kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "To_location",
                    models.CharField(
                        choices=[
                            ("hyderabad", "hyderabad"),
                            ("bangalore", "bangalore"),
                            ("chennai", "chennai"),
                            ("mumbai", "mumbai"),
                            ("kadapa", "kadapa"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("user_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=10)),
            ],
        ),
    ]
