# Generated by Django 5.0.7 on 2024-08-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appone", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="To_location",
            new_name="to_location",
        ),
        migrations.AddField(
            model_name="ticket",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("Vacation", "Vacation"),
                    ("Tovisit Temples", "Tovisit Temples"),
                    ("Short-term stay", "Short-term stay"),
                    ("Long-term stay", "Long-term stay"),
                    ("studies", "Studies"),
                    ("others", "others"),
                ],
                default=None,
                max_length=100,
            ),
        ),
    ]
